DATABASES_ENGINE = 'django.db.backends.postgresql_psycopg2'
DATABASES_NAME = 'mbp'
DATABASES_USER = 'postgres'
DATABASES_PASSWORD = 'pg'
DATABASES_HOST = '127.0.0.1'
DATABASES_PORT = 5432

ORIGIN = 'http://localhost:8000'
DEFAULT_XPUB = 'xpub6BmJBbHkjXnr82jg4JdNsGAzsZeyCzeXfPJo7UtmsMfiJ5hqB3xGnocSvfbAXGKoC8GCiTGM7mVR9QNWtECScVS1ANswyE7CvMFmk5UiQ8o'
